### ISSUE TITLE
Need help using the module

### ISSUE THREAD

**Issue by ege1** [inkblot/puppet-bind#47]
Sorry for opening an issue for that but I couldn't find the needed information nor did I find a contact address.

I'm trying to manage the whole bind set-up using this module and hiera. I already tried with building a profile that uses created_resources to use the hiera data, but didn't get it done.

Nevertheless as far as I understood your documentation it should be possible to using hiera directly to set-up bind and configure zones and DNS records.

Can you give me a rough example in using your module with hiera including some basic records (and maybe even a wildcard record)?

Kind Regards,

Erik

**Comment by inkblot** [comment]
Would it be possible for you to post the relevant parts of your code? I'd rather help debug that than produce a whole contrived example that may or may not illustrate a solution the problem you're experiencing.

**Comment by ege1** [comment]
The main question is how to use your module using hiera.

What I tried now looks like:

```yaml
bind::dnssec: false
profiles::dnsserver::dns_zones:
  example.com:
    zone_type: 'master'
    domain: 'example.com'
    allow_transfers:
      - '127.0.0.1'
      - '127.0.0.2'
    dynamic: true
    allow_updates:
      - '127.0.0.1'
profiles::dnsserver::dns_records:
    resource_record:
      name: 'www.example.com'
      record: 'www'
      ensure: 'present'
      type: 'A'
      data: '192.168.0.1'
      zone: 'example.com'
```

While the "profile::dnsserver" looks like:

```puppet
class profiles::dnsserver {
  include bind
  $dns_zones = hiera_hash(profiles::dnsserver::dns_zones)
  create_resources(bind::zone, $dns_zones)
  $dns_records = hiera_hash(profiles::dnsserver::dns_records)
  create_resources(resource_record, $dns_records)
```

But I think there should be a way to directly use hiera to configure these values, at least as far as I understood your documentation.

My idea was to configure the whole name server including all records through hiera.

Kind Regards,

Erik
